
spring:
  cloud:
    gateway:
      routes:

     
        # AUTH SERVICE
     
        - id: auth-service
          uri: lb://AUTH-SERVICE
          predicates:
            - Path=/auth/**,/oauth2/**,/.well-known/**,/auth/register
          filters:
            - name: RequestRateLimiter
              args:
                redis-rate-limiter.replenish-rate: 5
                redis-rate-limiter.burst-capacity: 10
                key-resolver: "#{@ipKeyResolver}"

        # USER SERVICE

        - id: user-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/users/**
          filters:
            - name: RequestRateLimiter
              args:
                redis-rate-limiter.replenish-rate: 10
                redis-rate-limiter.burst-capacity: 20
                key-resolver: "#{@ipKeyResolver}"

        # PAYMENT SERVICE
     
        - id: payment-service
          uri: lb://PAYMENT-SERVICE
          predicates:
            - Path=/subscription/**
          filters:
            - name: RequestRateLimiter
              args:
                redis-rate-limiter.replenish-rate: 5
                redis-rate-limiter.burst-capacity: 10
                key-resolver: "#{@ipKeyResolver}"








  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:8081/oauth2/jwks

  data:
    redis:
      host: localhost
      port: 6379

server:
  port: 8080

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,gateway
  endpoint:
    health:
      show-details: always

logging:
  level:
    org.springframework.cloud.gateway: INFO
    org.springframework.security: INFO



      
