server:
  port: 8083
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true



spring:
  jpa:
    hibernate:
      ddl-auto: none
  flyway:
    enabled: true
    locations: classpath:db/migration

  datasource:
    url: jdbc:postgresql://localhost:5432/smartremind_payment
    username: postgres
    password: avhijay10
    driver-class-name: org.postgresql.Driver

#kafka (Producer)

  kafka:
    bootstrap-servers: localhost:9092

    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
#Producer Mapping

      properties:
        spring.json.type.mapping: suscriptionCreated:com.smartremind.payment_service.events.SubscriptionActivationEvent
    
  



#payment retries
payment:
  retry:
    max-attempt: 3

  region:
    local-currency: "INR"



    


management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always




#Razorpay

razorpay:
  key-id: ${RAZORPAY_KEY_ID}
  key-secret: ${RAZORPAY_KEY_SECRET}

      
