
server:
  port: 8085

# Database
spring:
  jpa:
    hibernate:
      ddl-auto: none

  flyway:
    enabled: true
    locations: classpath:db/migration

  datasource:
    url: jdbc:postgresql://localhost:5432/smartremind_users
    username: postgres
    password: avhijay10
    driver-class-name: org.postgresql.Driver

  # kafka
  kafka:
    bootstrap-servers: localhost:9092

    consumer:
      group-id: user-service-group
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer

      # spring.json.use.type.headers: false
       # spring.json.use.type.headers: false
      # spring.json.value.default.type: com.smartremind.user_service.event.UserCreationEvent
      # (ignores the header of the event received from the producer
      # and instead uses the consumer-side event as the target type)
      # setting the default target for the consumer 
      properties:
        spring.json.trusted.packages: "com.smartremind.*"
        spring.json.type.mapping: userCreated:com.smartremind.user_service.event.UserCreationEvent
        spring.json.type.mapping: suscriptionCreated:com.smartremind.user_service.event.SubscriptionActivationEvent
     

# eureka
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true

  instance:
    prefer-ip-address: true

# health and management
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics

  endpoint:
    health:
      show-details: always

logging:
  level:
    root: INFO
    com.smartremind.user_service: DEBUG


